# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Web-board' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Web-board  
  pod 'Alamofire'
  pod 'SwiftyJSON'
  
  target 'Web-boardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Web-boardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
