//
//  CommentPresenter.swift
//  Web-board
//
//  Created by Tawisit Rungsimuntupong on 3/5/2562 BE.
//  Copyright (c) 2562 Tawisit Rungsimuntupong. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentPresentationLogic
{
    func presentComments(response: Comment.GetComments.Response)
    func reload()
}

class CommentPresenter: CommentPresentationLogic
{
    weak var viewController: CommentDisplayLogic?

    func presentComments(response: Comment.GetComments.Response)
    {
        let viewModel = Comment.GetComments.ViewModel(comments: response.comments)
        viewController?.displayComments(viewModel: viewModel)
    }
    
    func reload() {
        viewController?.reload()
    }
}
