//
//  CommentInteractor.swift
//  Web-board
//
//  Created by Tawisit Rungsimuntupong on 3/5/2562 BE.
//  Copyright (c) 2562 Tawisit Rungsimuntupong. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentBusinessLogic
{
    func getComments(request: Comment.GetComments.Request)
    func createComment(request: Comment.CreateComment.Request)
    func getCell(comments: [Comment.Comment], post: Post.Post, indexPath: IndexPath, tableView: UITableView) -> UITableViewCell
}

protocol CommentDataStore
{
}

class CommentInteractor: CommentBusinessLogic, CommentDataStore
{
    var presenter: CommentPresentationLogic?
    var worker: CommentWorker = CommentWorker()

    func getComments(request: Comment.GetComments.Request) {
        worker.getComments(postId: request.postId, completionHandler: {[weak self](comments) in
            let response = Comment.GetComments.Response(comments: comments)
            self?.presenter?.presentComments(response: response)
        })
    }
    
    func createComment(request: Comment.CreateComment.Request) {
        worker.createComment(request: request, completionHandler: {[weak self]() in
            self?.presenter?.reload()
        })
        
    }
    
    func getCell(comments: [Comment.Comment], post: Post.Post, indexPath: IndexPath, tableView: UITableView) -> UITableViewCell {
        var cell = UITableViewCell()
        if indexPath.row == 0 {
            if let postCommentCell = tableView.dequeueReusableCell(withIdentifier: "PostCommentCell", for: indexPath) as? PostCommentCell {
                postCommentCell.content.text = post.content
                postCommentCell.createBy.text = post.createBy
                postCommentCell.createDate.text = post.createDate != nil ? "Create date: \(CommonWorker.shared.dateString.string(from: post.createDate!))" : ""
                cell = postCommentCell
            }
            
        } else {
            if let commentCell = tableView.dequeueReusableCell(withIdentifier: "CommentCell", for: indexPath) as? CommentCell {
                let comment = comments[indexPath.row - 1]
                commentCell.content.text = comment.content
                commentCell.createBy.text = "Create by: \(comment.createBy)"
                commentCell.createDate.text = comment.createDate != nil ? "Create date: \(CommonWorker.shared.dateString.string(from: comment.createDate!))" : ""
                cell = commentCell
            }
        }
        
        return cell
    }
}
