//
//  CommentModels.swift
//  Web-board
//
//  Created by Tawisit Rungsimuntupong on 3/5/2562 BE.
//  Copyright (c) 2562 Tawisit Rungsimuntupong. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Comment
{
    // MARK: Use cases
    struct Comment {
        var id: Int
        var postId: Int
        var content: String
        var createDate: Date?
        var createBy: String
    }
    
    enum GetComments
    {
        struct Request
        {
            var postId: Int
        }
        struct Response
        {
            var comments: [Comment]
        }
        struct ViewModel
        {
            var comments: [Comment]
        }
    }
    
    enum CreateComment
    {
        struct Request
        {
            var content: String
            var postId: Int
        }
    }
}
