//
//  CommentWorker.swift
//  Web-board
//
//  Created by Tawisit Rungsimuntupong on 3/5/2562 BE.
//  Copyright (c) 2562 Tawisit Rungsimuntupong. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON

class CommentWorker
{
    fileprivate let commonWorker: CommonWorker = CommonWorker.shared
    
    func getComments(postId: Int, completionHandler: @escaping (_ comments: [Comment.Comment]) -> Void) {
        Alamofire.request("\(commonWorker.baseUrl)/comments/bypost/\(postId)", method: .get).responseJSON {
            response in
            
            switch response.result {
            case .success:
                do {
                    let json = try JSON(data: response.data!)
                    var commentDataList = [Comment.Comment]()
                    json.array?.forEach({ (comment) in
                        let createBy = comment["createdBy"].string ?? ""
                        let content = comment["content"].string ?? ""
                        let id = comment["id"].int ?? 0
                        let postId = comment["postId"].int ?? 0
    
                        let create_date = comment["createdDate"].string ?? ""
                        let createDate = self.commonWorker.dateTimeFormatter.date(from: create_date)
    
                        commentDataList.append(Comment.Comment(id: id, postId: postId, content: content, createDate: createDate, createBy: createBy))
                    })
                    
                    completionHandler(commentDataList)
                } catch {
                    print(error)
                }
                
                break
            case .failure(let error):
                print(error)
            }
        }
    }
    
    func createComment(request: Comment.CreateComment.Request, completionHandler: @escaping () -> Void) {
        let ipAddress = commonWorker.getIPAddress()
        
        let parameters: Parameters = ["content": request.content, "createdBy": ipAddress ?? "", "postId": request.postId]
        Alamofire.request("\(commonWorker.baseUrl)/comments/add", method: .post, parameters: parameters, encoding: JSONEncoding.default, headers: ["Content-Type": "application/json"]).responseData {
            response in
            
            switch response.result {
            case .success:
                print("create comment success")
                completionHandler()
                break
            case .failure(let error):
                print(error)
            }
        }
    }
}
