//
//  PostRouter.swift
//  Web-board
//
//  Created by Tawisit Rungsimuntupong on 1/5/2562 BE.
//  Copyright (c) 2562 Tawisit Rungsimuntupong. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostRoutingLogic
{
    func navigateToComment(source: PostViewController, post: Post.Post)
    func passDataToComment(destination: CommentViewController, post: Post.Post)
}

protocol PostDataPassing
{
    var dataStore: PostDataStore? { get }
}

class PostRouter: NSObject, PostRoutingLogic, PostDataPassing
{
    weak var viewController: PostViewController?
    var dataStore: PostDataStore?

    // MARK: Navigation
  
    func navigateToComment(source: PostViewController, post: Post.Post)
    {
        source.performSegue(withIdentifier: "Comment", sender: post)
    }
  
    // MARK: Passing data
  
    func passDataToComment(destination: CommentViewController, post: Post.Post)
    {
        destination.post = post
    }
}
