//
//  PostModels.swift
//  Web-board
//
//  Created by Tawisit Rungsimuntupong on 1/5/2562 BE.
//  Copyright (c) 2562 Tawisit Rungsimuntupong. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Post
{
    struct Post
    {
        var numberOfComments: Int
        var createDate: Date?
        var createBy: String
        var content: String
        var id: Int
        var lastCommentDate: Date?
    }
    
    enum GetPosts
    {
        enum Pagination {
            case next
            case previous
        }
        enum DisableButton {
            case previous
            case next
            case both
            case none
        }
        struct Request
        {
            var pagination: Pagination
            var isReload: Bool
        }
        struct Response
        {
            var posts: [Post]
            var disableButton: DisableButton
        }
        struct ViewModel
        {
            var posts: [Post]
        }
    }
    
    enum CreatePost
    {
        struct Request
        {
            var content: String
        }
    }

}
